development:
  adapter: enhanced_postgresql #for chatbot
  # adapter: async

test:
  adapter: test

production:
  adapter: enhanced_postgresql #for chatbot
  # adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: dress_me_up_production
